### ISSUE TITLE
miri doesn't drop values moved into closures with `let _ = x`

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#135]
The following code works fine if `drop(x)` is used instead of `let _ = x`. The closure function generated contains just a `_0 = ()` and a `return`. Trans probably does some magic, but I haven't been able to locate it.

```rust
struct Foo<'a>(&'a mut bool);

impl<'a> Drop for Foo<'a> {
    fn drop(&mut self) {
        *self.0 = true;
    }
}

fn f<T: FnOnce()>(t: T) {
    t()
}

fn main() {
    let mut ran_drop = false;
    {
        let x = Foo(&mut ran_drop);
        let x = move || { let _ = x; };
        f(x);
    }
    assert!(ran_drop);
}
```

**Comment by solson** [comment]
@oli-obk Weird... the closure body ought to explicitly drop the closure environment in MIR.

**Comment by solson** [comment]
I figured out the problem here.

`move || { let _ = x; };` never by-value uses any of its captures, so it's a closure whose inherent signature is `fn(&self)`. When we call it through `FnOnce::call_once` (in `f(x)`), it has to use [a shim](https://github.com/solson/miri/blob/eeae478e7428f40959d048adce14605c47a6d378/src/traits.rs#L56-L87).

Our shim acts like the following function, where `self` is the closure type and `body` is the closure fn:

```rust
fn call_once_shim(self) {
    body(&self)
    // NOTE: self is implicitly dropped at the end of scope.
}
```

As you can see in the shim code I linked above, we do add this `self` to a vec of `temporaries` to be freed when the stack frame is freed, but we don't ever execute the drop glue for it. (It's freed [here](https://github.com/solson/miri/blob/eeae478e7428f40959d048adce14605c47a6d378/src/eval_context.rs#L351-L356).)

**Comment by solson** [comment]
Note that if you force the closure to by-value use a separate value to remove Miri's use of the shim, then the closure's drop glue is properly called, as in [this test I added](https://github.com/solson/miri/blob/eeae478e7428f40959d048adce14605c47a6d378/tests/run-pass/closure-drop.rs#L16-L26).

**Comment by oli-obk** [comment]
Great analysis! I'll take this bug, drop code is my fault anyway ;)

**Comment by solson** [comment]
It would also be fixed once @arielb1's rewrite of these shims into explicit MIR bodies is done in rustc, but I'm not sure about the timeline on that. If it's hard to fix in Miri, we can wait, otherwise it's fine to do it now.
