### ISSUE TITLE
is `&*some_dangling_ptr` legal?

### ISSUE THREAD

**Issue by oli-obk** [solson/miri#244]
Right now miri ends up doing an alignment check on it, which will trigger the dangling pointer checks.

I think it should be totall fine, since it's a noop except for array -> slice and type -> trait, but even in those two cases the pointer itself is never read.

**Comment by RalfJung** [comment]
Ah, I did not realize alignment-checking implies dangling-pointer-checking. OTOH it's somewhat hard to actually check the alignment of dangling pointers since we no longer know which alignment the allocation had.

This also seems somewhat inconsistent since integer pointers are allowed.

Another trouble with this check was brought up in <https://github.com/rust-lang/rust/issues/27060#issuecomment-314966264>: It should be possible to create unaligned raw pointers e.g. to fields of a packed struct (and use them e.g. with the unaligned read/write intrinsics), but currently that doesn't work: `&mut x.field as *mut _` errors out before it gets a chance to turn the reference into a raw pointer.

@eddyb Which LLVM behavior makes it *not* sufficient to only check alignment on access? IIRC you mentioned that we have function arguments annotated telling LLVM "these are aligned pointer" -- so would it be enough to also check at the beginning of each function? (Something that I plan to do for all sorts of types anyway.)

**Comment by eddyb** [comment]
@RalfJung It's probably just the function boundary. The other stuff I was worried about doesn't seem to be used anymore.

**Comment by oli-obk** [comment]
More data: Mir optimizations simplify `&*x` to `x` in many (all?) cases.

**Comment by eddyb** [comment]
@oli-obk They do that on *references*, AFAIK, where it's a noop (in fact they should never be emitted in the first place, as `&T` has subtyping).

**Comment by RalfJung** [comment]
I see them emitted and optimized away frequently.

With #259 merged, `&*x` should be always permitted by miri, right?

**Comment by oli-obk** [comment]
Jup. We should probably add the two removed cfail tests as run-pass tests
