### ISSUE TITLE
Add configurable resource limits

### ISSUE THREAD

**Issue by solson** [solson/miri#37]
Eventually, we want rustc to be able to limit the amount of time spent evaluating a constant value, since Miri const eval could have infinite loops or simply very long calculations.

Thanks to the `EvalContext::step` interface, this should be pretty easy. Likely, we can just have a step count limit which will be configurable like rustc's `recursion_depth`.

**Comment by oli-obk** [comment]
There are more limits that make sense. e.g. a memory limit. Should be easy enough to track the amount of memory used by increasing/decreasing a counter whenever something is added to the allocation hash map.

Also stack depth should be limited, because I wager it's rather easy to end up filling the host memory by infinite recursion without triggering the execution or memory limit first.
